src/Web/Components/PeriodSummaryViewComponent.cs
using HotelSystem.SharedKernel.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Web.Interfaces;

namespace Web.Components
{
    public class PeriodSummaryViewComponent : ViewComponent
    {
        private readonly IManagerClient _managerClient;

        public PeriodSummaryViewComponent(IManagerClient managerClient)
        {
            _managerClient = managerClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                DateTime end = DateTime.Today;
                DateTime start = end.AddDays(-60);
                HttpResponseMessage responseMessage = await _managerClient.GetPeriodSummary(start, end);
                if (responseMessage.IsSuccessStatusCode)
                {
                    PeriodSummary complaints = await responseMessage.Content.ReadAsAsync<PeriodSummary>();
                    return View(complaints);
                }
                else
                {
                    TempData["_alert.type"] = "danger";
                    TempData["_alert.title"] = "Error";
                    TempData["_alert.body"] = responseMessage.ReasonPhrase;
                    return View();
                }
            }
            catch (Exception e)
            {
                TempData["_alert.type"] = "danger";
                TempData["_alert.title"] = "Error";
                TempData["_alert.body"] = e.Message;
                return View();
            }
        }
    }
}

src/Web/Components/SummaryViewComponent.cs
using HotelSystem.SharedKernel.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Web.Interfaces;

namespace Web.Components
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly IManagerClient _managerClient;

        public SummaryViewComponent(IManagerClient managerClient)
        {
            _managerClient = managerClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                HttpResponseMessage responseMessage = await _managerClient.GetSummary();
                if (responseMessage.IsSuccessStatusCode)
                {
                    SummaryViewModel complaints = await responseMessage.Content.ReadAsAsync<SummaryViewModel>();
                    return View(complaints);
                }
                else
                {
                    TempData["_alert.type"] = "danger";
                    TempData["_alert.title"] = "Error";
                    TempData["_alert.body"] = responseMessage.ReasonPhrase;
                    return View();
                }
            }
            catch (Exception e)
            {
                TempData["_alert.type"] = "danger";
                TempData["_alert.title"] = "Error";
                TempData["_alert.body"] = e.Message;
                return View();
            }
        }
    }
}

src/Web/Controllers/ManagerController.cs
namespace Web.Controllers
{
    using HotelSystem.SharedKernel.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Web.Extensions;
    using Web.Interfaces;

    [Authorize(Policy = "MANAGER")]
    public class ManagerController : Controller
    {
        private readonly IManagerClient _managerClient;
        private readonly IBookingClient _bookingClient;

        public ManagerController(IManagerClient managerClient, IBookingClient bookingClient)
        {
            _managerClient = managerClient;
            _bookingClient = bookingClient;
        }

        [HttpGet]
        public async Task<IActionResult> Complaints()
        {
            try
            {
                HttpResponseMessage responseMessage = await _managerClient.GetComplaints();
                if (responseMessage.IsSuccessStatusCode)
                {
                    ICollection<ComplaintViewModel> complaints = await responseMessage.Content.ReadAsAsync<ICollection<ComplaintViewModel>>();
                    return View(complaints);
                }
                else
                {
                    TempData["_alert.type"] = "danger";
                    TempData["_alert.title"] = "Error";
                    TempData["_alert.body"] = responseMessage.ReasonPhrase;
                    return View();
                }

            }
            catch(Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddRoom(Guid HotelId)
        {
            try
            {
                HotelViewModel hotel;
                HttpResponseMessage responseMessage = await _bookingClient.GetHotel(HotelId);
                if(responseMessage.IsSuccessStatusCode)
                {
                    hotel = await responseMessage.Content.ReadAsAsync<HotelViewModel>();
                    RoomViewModel model = new RoomViewModel()
                    {
                        HotelId = HotelId,
                        CreationTime = DateTime.UtcNow,
                        ModifiedDate = DateTime.UtcNow,
                        RoomNumber = hotel.NumberOfRooms + 1,
                        Id = Guid.NewGuid(),
                        HotelName = hotel.Name
                    };
                    ViewData["HotelName"] = hotel.Name;
                    return View(model);
                }
                else
                {
                    if(responseMessage.StatusCode == HttpStatusCode.NotFound || 
                        responseMessage.StatusCode == HttpStatusCode.BadRequest)
                    {
                        string message = await responseMessage.Content.ReadAsStringAsync();
                        return RedirectToAction(nameof(Rooms), new { HotelId })
                            .WithDanger("Error", message);
                    }
                    else
                    {
                        return RedirectToAction(nameof(Rooms), new { HotelId }).WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
            }
            catch(Exception e)
            {
                return RedirectToAction(nameof(Rooms), new { HotelId }).WithDanger("Error", e.Message);
            }
        }

        [HttpGet]
        public IActionResult AddHotel()
        {   
            HotelViewModel model = new HotelViewModel()
            {
                Id = Guid.NewGuid(),
                ManagerId = Helpers.Claims.GetUserID(HttpContext.User.Claims),
                CreationTime = DateTime.UtcNow,
                ModifiedDate = DateTime.UtcNow
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRoom(Guid HotelId,RoomViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    HttpResponseMessage responseMessage = await _managerClient.AddRoom(HotelId, model);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Hotels)).WithSuccess("Success", "Hotel Deleted.");
                    }
                    else
                    {
                        if (responseMessage.StatusCode == HttpStatusCode.BadRequest || responseMessage.StatusCode == HttpStatusCode.NotFound)
                        {
                            string message = await responseMessage.Content.ReadAsStringAsync();
                            return View().WithDanger("Error", message);
                        }
                        else
                        {
                            return View().WithDanger("Error", responseMessage.ReasonPhrase);
                        }
                    }
                }
                catch (Exception e)
                {
                    return View(model).WithDanger("Error", e.Message);
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddHotel(HotelViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    HttpResponseMessage responseMessage = await _managerClient.AddHotel( model);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Hotels)).WithSuccess("Success", "Hotel Deleted.");
                    }
                    else
                    {
                        if (responseMessage.StatusCode == HttpStatusCode.BadRequest || responseMessage.StatusCode == HttpStatusCode.NotFound)
                        {
                            string message = await responseMessage.Content.ReadAsStringAsync();
                            return View().WithDanger("Error", message);
                        }
                        else
                        {
                            return View().WithDanger("Error", responseMessage.ReasonPhrase);
                        }
                    }
                }
                catch(Exception e)
                {
                    return View(model).WithDanger("Error", e.Message);
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteRoom(Guid HotelId, Guid RoomId)
        {
            try
            {
                HttpResponseMessage responseMessage = await _managerClient.RemoveRoom(HotelId, RoomId);
                if (responseMessage.IsSuccessStatusCode)
                {
                    return View().WithSuccess("Success", "Room Deleted.");
                }
                else
                {
                    if (responseMessage.StatusCode == HttpStatusCode.BadRequest || responseMessage.StatusCode == HttpStatusCode.NotFound)
                    {
                        string message = await responseMessage.Content.ReadAsStringAsync();
                        return View().WithDanger("Error", message);
                    }
                    else
                    {
                        return View().WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
            }
            catch (Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpGet]
        public IActionResult Delete_Hotel(Guid Id)
        {
            return RedirectToAction(nameof(DeleteHotel), new { Id });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteHotel(Guid Id)
        {
            try
            {
                HttpResponseMessage responseMessage = await _managerClient.RemoveHotel(Id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    return View().WithSuccess("Success", "Hotel Deleted.");
                }
                else
                {
                    if (responseMessage.StatusCode == HttpStatusCode.BadRequest || responseMessage.StatusCode == HttpStatusCode.NotFound)
                    {
                        string message = await responseMessage.Content.ReadAsStringAsync();
                        return View().WithDanger("Error", message);
                    }
                    else
                    {
                        return View().WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
            }
            catch (Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRoom(Guid HotelId, Guid RoomId, RoomViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    HttpResponseMessage responseMessage = await _managerClient.RemoveRoom(HotelId, RoomId, model);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Hotels)).WithSuccess("Success", "Room Removed");
                    }
                    else
                    {
                        if (responseMessage.StatusCode == HttpStatusCode.BadRequest || responseMessage.StatusCode == HttpStatusCode.NotFound)

src/Web/Views/Manager/AddHotel.cshtml
@model HotelSystem.SharedKernel.ViewModels.HotelViewModel

@{
    ViewData["Title"] = "AddHotel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12 col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Manager" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-controller="Manager" asp-action="Hotels">Hotels</a></li>
			<li class="breadcrumb-item active"><a asp-controller="Manager" asp-action="AddHotel">Add Hotel</a></li>
        </ol>
    </div>
</div>


<h4 class="pb-1">Add Hotel</h4>

<hr />

<div class="row">
    <div class="col-md-5 col-sm-5">
        <form asp-action="AddHotel">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="PostalCode" class="control-label"></label>
                        <input asp-for="PostalCode" class="form-control" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Province" class="control-label"></label>
                        <input asp-for="Province" class="form-control" />
                        <span asp-validation-for="Province" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Rating" class="control-label"></label>
                        <select asp-for="Rating" class="form-control">
                            <option value="One_Star">One Star</option>
                            <option value="One_Star">Two Star</option>
                            <option value="One_Star">Three Star</option>
                            <option value="One_Star">Four Star</option>
                            <option value="One_Star">Five Star</option>
                        </select>
                        <span asp-validation-for="Rating" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Street" class="control-label"></label>
                        <input asp-for="Street" class="form-control" />
                        <span asp-validation-for="Street" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <input asp-for="Id" class="form-control" type="hidden" />
            <input asp-for="ManagerId" class="form-control" type="hidden" />
            <input asp-for="CreationTime" class="form-control" type="hidden" />
            <input asp-for="ModifiedDate" class="form-control" type="hidden" />
            <div class="row">
                <div class="col">
                    <div class="form-group pull-right">
                        <a asp-action="Hotels" asp-controller="Manager" class="align-bottom">Back to List</a>
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Web/Views/Manager/AddRoom.cshtml
@model HotelSystem.SharedKernel.ViewModels.RoomViewModel

@{
    ViewData["Title"] = "AddRoom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12 col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Manager" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-controller="Manager" asp-action="Rooms">Rooms</a></li>
            <li class="breadcrumb-item active"><a asp-controller="Manager" asp-action="AddRoom">Add Room</a></li>
        </ol>
    </div>
</div>

<h4 class="pb-1">Add Room</h4>

<hr />

<div class="row">
    <div class="col-md-5 col-sm-5">
        <form asp-action="AddRoom">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col">
                    <h5>@Html.DisplayFor(model => model.HotelName)</h5>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="RoomType" class="control-label"></label>
                        <select asp-for="RoomType" class="form-control" id="type">
                            <option value="" disabled>Select room type</option>
                            <option value="Single">Single</option>
                            <option value="Double">Double</option>
                            <option value="Triple">Triple</option>
                        </select>
                        <span asp-validation-for="RoomType" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label class="control-label">Number of beds</label>
                        <input id="capacity" asp-for="Capacity" class="form-control" readonly type="number"/>
                        <span asp-validation-for="Capacity" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Cost" class="control-label"></label>
                        <input id="cost" asp-for="Cost" class="form-control" readonly />
                        <span asp-validation-for="Cost" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group pull-right">
                        <a asp-action="Rooms" asp-controller="Manager" class="align-bottom pr-1">Back to List</a>
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            <input asp-for="CreationTime" class="form-control" type="hidden" />
            <input asp-for="HotelId" class="form-control" type="hidden" />
            <input asp-for="Id" class="form-control" type="hidden" />
            <input asp-for="ModifiedDate" class="form-control" type="hidden" />
            <input asp-for="RoomNumber" class="form-control" type="hidden"/>
            <input asp-for="HotelName" class="form-control" type="hidden" />
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#type').change(function () {
                var type = $(this).find("option:selected").val();
                if (type == "Single") {
                    $('#cost').val(300);
                    $('#capacity').val(1);
                }
                if (type == "Double") {
                    $('#cost').val(500);
                    $('#capacity').val(2);
                }
                if (type == "Triple") {
                    $('#cost').val(700);
                    $('#capacity').val(3);
                }
            });
        });
    </script>
}

src/Web/Views/Manager/Complaint.cshtml
@model ComplaintViewModel

@{
    ViewData["Title"] = "Complaint";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12 col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Manager</a></li>
            <li class="breadcrumb-item active"><a asp-controller="Manager" asp-action="Complaints">Complaints</a></li>
            <li class="breadcrumb-item active"><a href="#">Complaint</a></li>
        </ol>
    </div>
</div>

<h2>Complaint</h2>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Manager" asp-action="Complaint" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="BookingId" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="ComplainType" class="control-label"></label>
                <input asp-for="ComplainType" class="form-control" readonly/>
                <span asp-validation-for="ComplainType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsResolved"  /> @Html.DisplayNameFor(model => model.IsResolved)
                    </label>
                </div>
            </div>
            <div class="form-group pull-right">
                <a asp-action="Manager" asp-controller="Complaints" class="btn btn-outline-secondary">Back to List</a>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

src/Web/Views/Manager/Complaints.cshtml
@model IEnumerable<ComplaintViewModel>
@using Humanizer

@{
    ViewData["Title"] = "Complaints";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@functions
{
public BookingStatus GetStatus(string status)
{
    Enum.TryParse(status, out BookingStatus myStatus);
    return myStatus;
}
}

@if(Model == null)
{ 
<div class="row">
    <div class="col-sm-12 col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Manager</a></li>
            <li class="breadcrumb-item active"><a asp-controller="Manager" asp-action="Complaints">Complaints</a></li>
        </ol>
    </div>
</div>

<h4 class="pb-1">Guest Complaints</h4>


<hr />

<div class="row">
    <div class="col text-center">
        <img src="~/images/error/web_hi_res_512.png" class="img-fluid rounded" height="200" width="100" />
    </div>
</div>

}
else
{
<div class="row">
    <div class="col-md-12 col-sm-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ComplainType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        Resolution Status
                    </th>
                    <th>
                        Guest Level of Satisfaction
                    </th>
                    <th>
                        Last Modified
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ComplainType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @if (item.IsResolved == true)
                            {
                                <span class="text text-success">Resolved</span>
                            }
                            else
                            {
                                <span class="text text-info">Pending</span>
                            }
                        </td>
                        <td>
                            @if (item.IsResolved == true)
                            {

                                <a asp-controller="Manager" asp-action="Complaint" asp-route-Id="@item.Id" class="btn btn-primary">Resolve complaint</a>
                            }
                            else
                            {

                            }
                        </td>
                        <td>
                            <span>@item.ModifiedDate.Humanize(true, DateTime.UtcNow, new CultureInfo("en-ZA"))</span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
}

src/Web/Views/Manager/DeleteRoom.cshtml
@model HotelSystem.SharedKernel.ViewModels.RoomAmenityViewModel

@{
    ViewData["Title"] = "DeleteRoom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteRoom</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RoomAmenityViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AmenityId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AmenityId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoomId)
        </dd>
    </dl>
    
    <form asp-action="DeleteRoom">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/Web/Views/Manager/Hotels.cshtml
@model IEnumerable<HotelSystem.SharedKernel.ViewModels.HotelViewModel>

@{
    ViewData["Title"] = "Hotels";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-sm-12 col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Manager" asp-action="Index">Dashboard</a></li>
            <li class="breadcrumb-item active"><a asp-controller="Manager" asp-action="Hotels">Hotels</a></li>
        </ol>
    </div>
</div>

<h4 class="pb-1">Your Hotels</h4>


<p>
    <span class="text text-lowercase">
        <a asp-controller="Manager" asp-action="AddHotel">
            <i class=" fa fa-plus"></i>
            Add new hotel
        </a>
    </span>
</p>

@if (Model == null)
{
    <hr />

    <div class="row">
        <div class="col text-center">
            <img src="~/images/placeholder/web_hi_res_512.png" class="img-fluid rounded" height="200" width="100" />
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <a asp-action="HotelDetails" asp-controller="Manager" asp-route-Id="@item.Id">Details</a> |
                                <a asp-action="Delete_Hotel" asp-controller="Manager" asp-route-Id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

src/Web/Views/Manager/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="pb-1">Dashboard</h4>

<hr />

<div class="row">
    <div class="col-sm-3 col-md-2">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a class="nav-item" asp-controller="Manager" asp-action="Hotels">Hotels</a>
            </li>
            <li class="nav-item">
                <a class="nav-item" asp-controller="Manager" asp-action="Rooms">Rooms</a>
            </li>
            <li class="nav-item">
                <a class="nav-item" asp-controller="Manager" asp-action="Amenities">Amenities</a>
            </li>
            <li class="nav-item">
                <a class="nav-item" asp-controller="Manager" asp-action="Complaints">Complaints</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9 col-sm-9 border-left">
        @await  Component.InvokeAsync("Summary")
        <hr>
        @await  Component.InvokeAsync("PeriodSummary")
    </div>
</div>