src/Web/Components/BookingsViewComponent.cs
using HotelSystem.SharedKernel.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Web.Interfaces;

namespace Web.Components
{
    public class BookingsViewComponent : ViewComponent
    {
        private readonly IBookingClient _bookingClient;
        private readonly IHttpContextAccessor _contextAccessor;

        public BookingsViewComponent(IBookingClient bookingClient, IHttpContextAccessor contextAccessor)
        {
            _bookingClient = bookingClient;
            _contextAccessor = contextAccessor;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                Guid Id = Helpers.Claims.GetUserID(_contextAccessor.HttpContext.User.Claims);
                HttpResponseMessage responseMessage = await _bookingClient.FrontDeskBookings(Id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    ICollection<BookingViewModel> bookings = await responseMessage.Content.ReadAsAsync<ICollection<BookingViewModel>>();
                    return View(bookings);
                }
                else
                {
                    TempData["_alert.type"] = "danger";
                    TempData["_alert.title"] = "Error";
                    TempData["_alert.body"] = responseMessage.ReasonPhrase;
                    return View();
                }
            }
            catch (Exception e)
            {
                TempData["_alert.type"] = "danger";
                TempData["_alert.title"] = "Error";
                TempData["_alert.body"] = e.Message;
                return View();
            }
        }
    }
}

src/Web/Controllers/FrontDeskController.cs
namespace Web.Controllers
{
    using HotelSystem.SharedKernel.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Web.Extensions;
    using Web.Interfaces;

    [Authorize(Policy = "FRONTDESK")]
    public class FrontDeskController : Controller
    {
        private readonly IBookingClient _bookingClient;

        public FrontDeskController(IBookingClient bookingClient)
        {
            _bookingClient = bookingClient;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CheckIn(Guid Id)
        {
            try
            {
                HttpResponseMessage responseMessage = await _bookingClient.GetBooking(Id, true);
                if(responseMessage.IsSuccessStatusCode)
                {
                    BookingViewModel booking = await responseMessage.Content.ReadAsAsync<BookingViewModel>();
                    return View(booking);
                }
                else
                {
                    return View().WithDanger("Error", responseMessage.ReasonPhrase);
                }
            }
            catch (Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CheckIn(BookingViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    HttpResponseMessage responseMessage = await _bookingClient.CheckIn(model);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index)).WithSuccess("Success", "Checked In");
                    }
                    else
                    {
                        return View(model).WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
                catch (Exception e)
                {
                    return View(model).WithDanger("Error", e.Message);
                }
            }
            else
            {
                return View(model);
            }
        }
            

        [HttpGet]
        public async Task<IActionResult> CheckOut(Guid Id)
        {
            try
            {
                HttpResponseMessage responseMessage = await _bookingClient.GetBooking(Id, true);
                if (responseMessage.IsSuccessStatusCode)
                {
                    BookingViewModel booking = await responseMessage.Content.ReadAsAsync<BookingViewModel>();
                    return View(booking);
                }
                else
                {
                    return View().WithDanger("Error", responseMessage.ReasonPhrase);
                }
            }
            catch (Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CheckOut(BookingViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    HttpResponseMessage responseMessage = await _bookingClient.CheckOut(model);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index)).WithSuccess("Success", "Checked Out");
                    }
                    else
                    {
                        return View(model).WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
                catch (Exception e)
                {
                    return View(model).WithDanger("Error", e.Message);
                }
            }
            else
            {
                return View(model);
            }
            
        }
    }
}

src/Web/Views/FrontDesk/CheckIn.cshtml
@model HotelSystem.SharedKernel.ViewModels.BookingViewModel

@{
    ViewData["Title"] = "Check In";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12 col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active"><a asp-controller="FrontDesk" asp-action="Index">Front Desk</a></li>
        </ol>
    </div>
</div>

<h4 class="pb-1">Check In</h4>

<hr />

<form asp-controller="FrontDesk" asp-action="CheckIn" method="post">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <div asp-validation-summary="ModelOnly" class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times</span></button>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="Arrival" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-calendar rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input type="datetime" asp-for="Arrival" class="form-control" readonly />
                            <span asp-validation-for="Arrival" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="Departure" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-calendar rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input type="datetime" asp-for="Departure" class="form-control" readonly />
                            <span asp-validation-for="Departure" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="HotelName" class="col-form-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-hotel rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input asp-for="HotelName" class="form-control" readonly />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="NumberOfGuests" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-users rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input asp-for="NumberOfGuests" class="form-control" readonly />
                            <span asp-validation-for="NumberOfGuests" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="Status" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-map-marker bg-info text-light input-group-text"></i>
                            </div>
                            <select asp-for="Status" class="form-control">
                                <option value="" disabled selected>Check in guest</option>
                                <option value="CheckedIn">Check In</option>
                            </select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <div class="btn-group btn-block">
                            <button type="button" class="btn btn-block">
                                Selected Rooms
                                <span class="sr-only">Selected Rooms</span>
                            </button>
                            <button type="button" class="bg-info text-light btn">@Model.NumSelectedRooms</button>
                        </div>
                    </div>
                </div>
            </div>
            <input asp-for="CheckInPerson" type="hidden" readonly />
            <input asp-for="CheckOutPerson" type="hidden" readonly />
            <input asp-for="NumSelectedRooms" class="form-control" type="hidden" readonly />
            <input asp-for="ModifiedDate" class="form-control" type="hidden" readonly />
            <input asp-for="CreationTime" class="form-control" type="hidden" readonly />
            <input asp-for="HotelId" class="form-control" type="hidden" readonly />
            <input asp-for="Id" class="form-control" type="hidden" readonly />
            <input asp-for="BookerId" class="form-control" type="hidden" readonly />
            <input asp-for="CheckInCheckList.BookingId" value="@Model.Id" type="hidden" readonly />
        </div>
        <div class="col-md-5 border-left">
            <h5 class="pb-1">Check List</h5>
            <div class="row">
                <div class="col">
                    <span>
                        <label>Keys</label>
                    </span>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <i class="fa fa-key bg-info text-light input-group-text"></i>
                        </div>
                        <select class="form-control" id="keys">
                            <option value="" selected>Select</option>
                            <option value="true">Yes</option>
                            <option value="false">No</option>
                        </select>
                        <input type="hidden" asp-for="CheckInCheckList.KeysReceived" id="keysInput" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <span>
                        <label>Amenities</label>
                    </span>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <i class="fa fa-info bg-info text-light input-group-text"></i>
                        </div>
                        <select class="form-control" id="amenities">
                            <option value="" selected>Select</option>
                            <option value="true">Yes</option>
                            <option value="false">No</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <span>
                        <label>Printed Invoice</label>
                    </span>
                    <div class="input-group">
                        <div class="input-group-append">
                            <i class="fa fa-envelope text-light bg-info input-group-text"></i>
                        </div>
                        <select class="form-control" id="printed">
                            <option value="" selected>Select</option>
                            <option value="true">Yes</option>
                            <option value="false">No</option>
                        </select>
                        <input type="hidden" asp-for="CheckInCheckList.PrintedRecepiet" id="printedInput" />
                    </div>
                </div>
            </div>
            <div class="row" style="visibility:hidden" id="invoice">
                <div class="col">
                    <div class="btn-group btn-block">
                        <a asp-action="CheckedInInvoice" asp-controller="FrontDesk" asp-route-Id="@Model.Id" class="bg-info text-light btn"><i class="fa fa-download"></i></a>
                        <a class="btn btn-block" asp-action="CheckedInInvoice" asp-controller="CheckedInInvoice" asp-route-Id="@Model.Id">
                            Download Invoice
                            <span class="sr-only">Download Invoice</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group pull-right">
                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary">Cancel</a>
                <button name="command" type="submit" value="ConfirmBooking" class="btn btn-primary" id="confirm">Proceed</button>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
                $(document).ready(function () {

                    //KeysReceived
                    $('#keys').change(function () {
                        var $option = $(this).find('option:selected');
                        var value = $option.val();
                        if (value == 'true') {
                            $('#keysInput').val(value);
                            $('#keysInput').attr('checked', true);
                        }
                        else {
                            $('#keysInput').val(value);
                            $('#keysInput').prop('checked', false);
                        }
                    });

                    //AllAmenities
                    $('#amenities').change(function () {
                        var $option = $(this).find('option:selected');
                        var value = $option.val();
                        if (value == 'true') {
                            $('#amenitiesInput').val(value);
                            $('#amenitiesInput').attr('checked', true);
                        }
                        else {
                            $('#amenitiesInput').val(value);
                            $('#amenitiesInput').prop('checked', false);
                        }
                    });

                    //Printed
                    $('#printed').change(function () {
                        var $option = $(this).find('option:selected');
                        var value = $option.val();
                        if (value == 'true') {
                            $('#printedInput').val(value);
                            $('#printedInput').attr('checked', true);
                            $('#invoice').css('visibility', 'hidden');
                        }
                        else {
                            $('#printedInput').val(value);
                            $('#printedInput').prop('checked', false);
                            $('#invoice').css('visibility', 'display');
                        }
                    });
                });
    </script>
}

src/Web/Views/FrontDesk/CheckOut.cshtml
@model HotelSystem.SharedKernel.ViewModels.BookingViewModel

@{
    ViewData["Title"] = "Check Out";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12 col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active"><a asp-controller="FrontDesk" asp-action="Index">Front Desk</a></li>
        </ol>
    </div>
</div>

<h4 class="pb-1">Check Out</h4>

<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-controller="FrontDesk" asp-action="CheckOut" method="post">
            <div class="form-group">
                <div asp-validation-summary="ModelOnly" class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times</span></button>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="Arrival" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-calendar rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input type="datetime" asp-for="Arrival" class="form-control" readonly />
                            <span asp-validation-for="Arrival" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="Departure" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-calendar rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input type="datetime" asp-for="Departure" class="form-control" readonly />
                            <span asp-validation-for="Departure" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="HotelName" class="col-form-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-hotel rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input asp-for="HotelName" class="form-control" readonly />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="NumberOfGuests" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-users rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input asp-for="NumberOfGuests" class="form-control" readonly />
                            <span asp-validation-for="NumberOfGuests" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <span>
                            <label asp-for="Status" class="control-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-map-marker bg-info text-light input-group-text"></i>
                            </div>
                            <select asp-for="Status">
                                <option value="" disabled selected>Check out guest</option>
                                <option value="CheckedOut">Check Out</option>
                            </select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <div class="btn-group btn-block">
                            <button type="button" class="btn btn-block">
                                Selected Rooms
                                <span class="sr-only">Selected Rooms</span>
                            </button>
                            <button type="button" class="bg-info text-light btn">@Model.NumSelectedRooms</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group pull-right">
                        <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary">Cancel</a>
                        <button name="command" type="submit" value="ConfirmBooking" class="btn btn-primary" id="confirm">Proceed</button>
                    </div>
                </div>
            </div>
            <input asp-for="CheckInPerson" type="hidden" readonly />
            <input asp-for="CheckOutPerson" type="hidden" readonly />
            <input asp-for="NumSelectedRooms" class="form-control" type="hidden" readonly />
            <input asp-for="ModifiedDate" class="form-control" type="hidden" readonly />
            <input asp-for="CreationTime" class="form-control" type="hidden" readonly />
            <input asp-for="HotelId" class="form-control" type="hidden" readonly />
            <input asp-for="Id" class="form-control" type="hidden" readonly />
            <input asp-for="BookerId" class="form-control" type="hidden" readonly />
        </form>
    </div>
</div>

src/Web/Views/FrontDesk/Index.cshtml
@{ 
    ViewData["Title"] = "Front Desk";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="pb-1">Front Desk</h4>

<hr />

<div class="row">
    <div class="col-sm-3 col-md-2">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a class="nav-item" asp-controller="FrontDesk" asp-action="Index">Front Desk</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9 col-sm-9 border-left">
        @await  Component.InvokeAsync("Bookings")
    </div>
</div>