src/Web/Components/PeriodSummaryViewComponent.cs
using HotelSystem.SharedKernel.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Web.Interfaces;

namespace Web.Components
{
    public class PeriodSummaryViewComponent : ViewComponent
    {
        private readonly IManagerClient _managerClient;

        public PeriodSummaryViewComponent(IManagerClient managerClient)
        {
            _managerClient = managerClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                DateTime end = DateTime.Today;
                DateTime start = end.AddDays(-60);
                HttpResponseMessage responseMessage = await _managerClient.GetPeriodSummary(start, end);
                if (responseMessage.IsSuccessStatusCode)
                {
                    PeriodSummary complaints = await responseMessage.Content.ReadAsAsync<PeriodSummary>();
                    return View(complaints);
                }
                else
                {
                    TempData["_alert.type"] = "danger";
                    TempData["_alert.title"] = "Error";
                    TempData["_alert.body"] = responseMessage.ReasonPhrase;
                    return View();
                }
            }
            catch (Exception e)
            {
                TempData["_alert.type"] = "danger";
                TempData["_alert.title"] = "Error";
                TempData["_alert.body"] = e.Message;
                return View();
            }
        }
    }
}

src/Web/Components/SummaryViewComponent.cs
using HotelSystem.SharedKernel.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Web.Interfaces;

namespace Web.Components
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly IManagerClient _managerClient;

        public SummaryViewComponent(IManagerClient managerClient)
        {
            _managerClient = managerClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                HttpResponseMessage responseMessage = await _managerClient.GetSummary();
                if (responseMessage.IsSuccessStatusCode)
                {
                    SummaryViewModel complaints = await responseMessage.Content.ReadAsAsync<SummaryViewModel>();
                    return View(complaints);
                }
                else
                {
                    TempData["_alert.type"] = "danger";
                    TempData["_alert.title"] = "Error";
                    TempData["_alert.body"] = responseMessage.ReasonPhrase;
                    return View();
                }
            }
            catch (Exception e)
            {
                TempData["_alert.type"] = "danger";
                TempData["_alert.title"] = "Error";
                TempData["_alert.body"] = e.Message;
                return View();
            }
        }
    }
}

src/Web/Controllers/BookingController.cs
namespace Web.Controllers
{
    using FluentValidation.Results;
    using HotelSystem.SharedKernel;
    using HotelSystem.SharedKernel.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Rotativa.AspNetCore;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Web.Extensions;
    using Web.Interfaces;
    using Web.Models;
    using Web.Validation;
    using Web.ViewModels;

    [Authorize(Policy = "GUEST")]
    public class BookingController : Controller
    {
        private readonly IBookingClient _bookingClient;

        private readonly ILogger<BookingController> _logger;

        public BookingController(IBookingClient bookingClient, ILogger<BookingController> logger)
        {
            _bookingClient = bookingClient;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Complaints()
        {
            try
            {
                Guid Id = Helpers.Claims.GetUserID(HttpContext.User.Claims);
                HttpResponseMessage responseMessage = await _bookingClient.GetComplaints(Id);
                if(responseMessage.IsSuccessStatusCode)
                {
                    ICollection<ComplaintViewModel> complaints = await responseMessage.Content.ReadAsAsync<ICollection<ComplaintViewModel>>();
                    return View(complaints);
                }
                else
                {
                    return View().WithDanger("Error", responseMessage.ReasonPhrase);
                }
            }
            catch(Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> RateComplaintResolution(Guid Id, Guid bookingId)
        {
            try
            {
                HttpResponseMessage responseMessage = await _bookingClient.GetComplaint(Id, bookingId);
                if(responseMessage.IsSuccessStatusCode)
                {
                    ComplaintViewModel model = await responseMessage.Content.ReadAsAsync<ComplaintViewModel>();
                    return View(model);
                }
                else
                {
                    return View().WithDanger("Error", responseMessage.ReasonPhrase);
                }
            }
            catch(Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> RateComplaintResolution(ComplaintViewModel model)
        {
            ComplaintRatingValidator validations = new ComplaintRatingValidator();
            ValidationResult validationResult = validations.Validate(model);
            if (!validationResult.IsValid)
            {
                foreach (ValidationFailure error in validationResult.Errors)
                {
                    ModelState.AddModelError("", error.ErrorMessage);
                }
                return View(model);
            }
            else
            {
                try
                {
                    HttpResponseMessage responseMessage_1 = await _bookingClient.GetBooking(model.BookingId, true);
                    if(responseMessage_1.IsSuccessStatusCode)
                    {
                        BookingViewModel bookingViewModel = await responseMessage_1.Content.ReadAsAsync<BookingViewModel>();
                        bookingViewModel.NewComplaint = new ComplaintViewModel()
                        {
                            BookingId = model.BookingId,
                            LevelOfSatisfaction = model.LevelOfSatisfaction,
                            Id = model.Id,
                            ModifiedDate = model.ModifiedDate,
                            ComplainType = model.ComplainType,
                            CreationTime = model.CreationTime,
                            IsResolved = model.IsResolved,
                            Description = model.Description
                        };
                        HttpResponseMessage responseMessage = await _bookingClient.RateComplaintResolution(bookingViewModel);
                        if (responseMessage.IsSuccessStatusCode)
                        {
                            return RedirectToAction(nameof(Complaints), new { Id = model.BookingId }).WithSuccess("Success", "Complaint rated");
                        }
                        else
                        {
                            return View().WithDanger("Error", responseMessage.ReasonPhrase);
                        }
                    }
                    else
                    {
                        return View().WithDanger("Error", responseMessage_1.ReasonPhrase);
                    }
                    
                }
                catch(Exception e)
                {
                    return View().WithDanger("Error", e.Message);
                }
            }
        }

        [HttpGet]
        public async Task<IActionResult> Complaint(Guid Id)
        {
            try
            {
                HttpResponseMessage responseMessage = await _bookingClient.GetBooking(Id, true);
                if(responseMessage.IsSuccessStatusCode)
                {
                    ComplaintViewModel model = new ComplaintViewModel()
                    {
                        BookingId = Id,
                        IsResolved = false
                    };
                    return View(model);
                }
                else
                {
                    return View().WithDanger("Error", responseMessage.ReasonPhrase);
                }
            }
            catch(Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Complaint(ComplaintViewModel complaintViewModel)
        {
            if(complaintViewModel.BookingId != Guid.Empty)
            {
                ComplaintValidator validations = new ComplaintValidator();
                ValidationResult validationResult = validations.Validate(complaintViewModel);
                if (!validationResult.IsValid)
                {
                    foreach (ValidationFailure error in validationResult.Errors)
                    {
                        ModelState.AddModelError("", error.ErrorMessage);
                    }
                    return View(complaintViewModel);
                }
                else
                {
                    HttpResponseMessage responseMessage = await _bookingClient.GetBooking(complaintViewModel.BookingId, true);
                    if(responseMessage.IsSuccessStatusCode)
                    {
                        BookingViewModel booking = await responseMessage.Content.ReadAsAsync<BookingViewModel>();
                        booking.NewComplaint = new ComplaintViewModel()
                        {
                            BookingId = complaintViewModel.BookingId,
                            IsResolved = complaintViewModel.IsResolved,
                            ComplainType = complaintViewModel.ComplainType,
                            Description = complaintViewModel.Description
                        };
                        HttpResponseMessage responseMessage_1 = await _bookingClient.AddComplaint(booking);
                        if(responseMessage_1.IsSuccessStatusCode)
                        {
                            return RedirectToAction(nameof(Bookings)).WithSuccess("Success", "Complaint made");
                        }
                        else
                        {
                            return View(complaintViewModel).WithDanger("Error", responseMessage_1.ReasonPhrase);
                        }
                    }
                    else
                    {
                        return View(complaintViewModel).WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
            }
            else
            {
                return RedirectToAction(nameof(Bookings)).WithDanger("Error","Choose valid booking");
            }
        }

        [HttpGet]
        public IActionResult Book()
        {
            try
            {
                _logger.LogInformation(LoggingEvents.GetItem, $"Get Booking");
                BookingViewModel model = BookingFactory.GetBookingViewModel(HttpContext);
                model.BookerId = Helpers.Claims.GetUserID(HttpContext.User.Claims);
                model = BookingFactory.GenerateInvoice(model);
                model.Payment = new PaymentViewModel()
                {
                    Id = Guid.NewGuid(),
                    InvoiceId = model.Invoice.Id,
                    AmountPaid = model.Invoice.Total()
                };
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogTrace(new EventId(LoggingEvents.ItemsError, "ItemsError"), e, "An exception occured");
                return RedirectToAction("Index", "Home").WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Book(BookingViewModel model)
        {
            BookingFactory.ClearAll(HttpContext);
            if (ModelState.IsValid)
            {
                try
                {
                    BookingSubmitValidator validationRules = new BookingSubmitValidator();
                    ValidationResult result = validationRules.Validate(model);
                    if (!result.IsValid)
                    {
                        foreach (ValidationFailure error in result.Errors)
                            ModelState.AddModelError("", error.ErrorMessage);
                        return View(model);

src/Web/Controllers/FrontDeskController.cs
namespace Web.Controllers
{
    using HotelSystem.SharedKernel.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Web.Extensions;
    using Web.Interfaces;

    [Authorize(Policy = "FRONTDESK")]
    public class FrontDeskController : Controller
    {
        private readonly IBookingClient _bookingClient;

        public FrontDeskController(IBookingClient bookingClient)
        {
            _bookingClient = bookingClient;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CheckIn(Guid Id)
        {
            try
            {
                HttpResponseMessage responseMessage = await _bookingClient.GetBooking(Id, true);
                if(responseMessage.IsSuccessStatusCode)
                {
                    BookingViewModel booking = await responseMessage.Content.ReadAsAsync<BookingViewModel>();
                    return View(booking);
                }
                else
                {
                    return View().WithDanger("Error", responseMessage.ReasonPhrase);
                }
            }
            catch (Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CheckIn(BookingViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    HttpResponseMessage responseMessage = await _bookingClient.CheckIn(model);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index)).WithSuccess("Success", "Checked In");
                    }
                    else
                    {
                        return View(model).WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
                catch (Exception e)
                {
                    return View(model).WithDanger("Error", e.Message);
                }
            }
            else
            {
                return View(model);
            }
        }
            

        [HttpGet]
        public async Task<IActionResult> CheckOut(Guid Id)
        {
            try
            {
                HttpResponseMessage responseMessage = await _bookingClient.GetBooking(Id, true);
                if (responseMessage.IsSuccessStatusCode)
                {
                    BookingViewModel booking = await responseMessage.Content.ReadAsAsync<BookingViewModel>();
                    return View(booking);
                }
                else
                {
                    return View().WithDanger("Error", responseMessage.ReasonPhrase);
                }
            }
            catch (Exception e)
            {
                return View().WithDanger("Error", e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CheckOut(BookingViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    HttpResponseMessage responseMessage = await _bookingClient.CheckOut(model);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index)).WithSuccess("Success", "Checked Out");
                    }
                    else
                    {
                        return View(model).WithDanger("Error", responseMessage.ReasonPhrase);
                    }
                }
                catch (Exception e)
                {
                    return View(model).WithDanger("Error", e.Message);
                }
            }
            else
            {
                return View(model);
            }
            
        }
    }
}

src/Web/Views/Shared/_Dashboard.cshtml
<h4 class="pb-1">Dashboard</h4>

<hr />

<div class="row">
    <div class="col-sm-3 col-md-2">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a class="nav-item" asp-controller="Manager" asp-action="Hotels">Hotels</a>
            </li>
            <li class="nav-item">
                <a class="nav-item" asp-controller="Manager" asp-action="Rooms">Rooms</a>
            </li>
            <li class="nav-item">
                <a class="nav-item" asp-controller="Manager" asp-action="Amenities">Amenities</a>
            </li>
            <li class="nav-ite">
                <a class="nav-item" asp-controller="Manager" asp-action="Complaints">Complaints</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9 col-sm-9 border-left">
        @await Component.InvokeAsync("Summary")
        <hr>
        @await Component.InvokeAsync("PeriodSummary")
    </div>
</div>

src/Web/Views/Shared/_DownloadLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blue Orb Hotel</title>
    <link rel="icon" type="image/x-icon" href="~/faveicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/faveicon.ico" />
    <link rel="stylesheet" href="~/css/font-awesome.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/css/normalize.css" type="text/css" />
    <link rel="stylesheet" href="~/css/flatpickr.css" type="text/css" />
</head>
<body>

    <main role="main" class="container">
        <div class="row">
            <div class="col-sm-10 col-md-10">
                @RenderBody()
            </div>
        </div>
    </main>

    <script src="~/js/popper.js"></script>
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/alert.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blue Orb Hotel</title>
    <link rel="icon" type="image/x-icon" href="~/faveicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/faveicon.ico" />
    <link rel="stylesheet" href="~/css/font-awesome.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/css/normalize.css" type="text/css" />
    <link rel="stylesheet" href="~/css/flatpickr.css" type="text/css" />
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a href="~/">
            <span class="navbar-brand">
                <img src="~/icon.png" class="icon-banner">
                Blue Orbs Hotel
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <partial name="_LoginPartial" />
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <br />
        <partial name="_StatusMessages" />
        <br />
        <div class="row">
            <div class="col-sm-10 col-md-10">
                @RenderBody()
            </div>
            <div class="col-sm-2 col-md-2">
                <ul class="breadcrumb nav nav-pills nav-tabs flex-column">
                    <li class="nav-item dropdown">
                        <a class="nav-link"  href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Home
                        <span class="caret pull-right dropdown-toggle"></span>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="Home" asp-action="Index">Index</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="About">About</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="Contact">Contact</a>
                            <a class="dropdown-item" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </div>
                    </li>
                    <partial name="_SideNavPartial" />
                </ul>
            </div>
        </div>
    </main>

    <script src="~/js/popper.js"></script>
    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/alert.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/Web/Views/Shared/_SearchBooking.cshtml
@model CheckInOutViewModel


    <div class="row">
        <div class="col">
            <form asp-controller="Home" asp-action="Search" method="post">
                <div class="row">
                    <div class="col-12 col-sm pr-sm-0">
                        <span>
                            <label asp-for="Arrival" class="col-form-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-calendar rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input id="arrival" asp-for="Arrival" class="form-control travel-date" data-input placeholder="Arrival date" />
                            <span asp-validation-for="Arrival" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 col-sm pr-sm-0">
                        <span>
                            <label asp-for="Departure" class="col-form-label"></label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-calendar rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input id="departure" asp-for="Departure" class="form-control travel-date" data-input placeholder="Departure date" />
                            <span asp-validation-for="Departure" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm pr-sm-0">
                        <span>
                            <label class="col-form-label">Email</label>
                        </span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <i class="fa fa-envelope rounded bg-info text-light input-group-text"></i>
                            </div>
                            <input asp-for="Email" class="form-control" placeholder="Email" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-sm pr-sm-0">
                        <br />
                        <input type="submit" value="Search for booking" class="btn btn-primary btn-block">
                    </div>
                </div>
            </form>
        </div>
    </div>

src/Web/Views/Shared/_SideNavPartial.cshtml
@inject IUserClaims claims


@if (User.Identity.IsAuthenticated)
{

    @if (claims.IsManager())
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Manager
                <span class="caret pull-right dropdown-toggle"></span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="Manager" asp-action="Index">Dashboard</a>
            </div>
        </li>
    }
    else if (claims.IsFrontDesk())
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Front Desk
                <span class="caret pull-right dropdown-toggle"></span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="FrontDesk" asp-action="Index">Front Desk</a>
            </div>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Booking
                <span class="caret pull-right dropdown-toggle"></span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="Booking" asp-action="Bookings">Your Bookings</a>
                <a class="dropdown-item" asp-controller="Home" asp-action="Index">Create Booking</a>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Complaints
                <span class="caret pull-right dropdown-toggle"></span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="Booking" asp-action="Complaints">Your Complaints</a>
                <a class="dropdown-item" asp-controller="Booking" asp-action="Bookings">Create Complaint</a>
            </div>
        </li>
    }
    <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Account
            <span class="caret pull-right dropdown-toggle"></span>
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-controller="Account" asp-action="Profile">Profile</a>
            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a>
        </div>
    </li>
}
else
{
    <li class="nav-item dropdown">
        <a class="nav-link" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Account
            <span class="caret pull-right dropdown-toggle"></span>
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-controller="Account" asp-action="Register">Register</a>
            <a class="dropdown-item" asp-controller="Account" asp-action="Login">Login</a>
            <a class="dropdown-item" asp-controller="Account" asp-action="ForgotPassword">Forgot Password</a>
        </div>
    </li>
}

src/Web/Views/Shared/_StatusMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}
@if (!string.IsNullOrEmpty(type))
{
    <div class="alert alert-@type alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times</span></button>
        <p><strong>@title</strong><br />@body</p>
    </div>
}